### ISSUE TITLE
Validate production Fedora migration

### ISSUE THREAD

**Issue by kbowaterskelly** [emory-libraries/OpenEmory#81]
See our first try validation results in #69 and additional notes in the [migration work log](https://docs.google.com/document/d/1qnauwDdlkflJ_I7T8y8CJ6gNEU7jjQT0dZ6olTLoPdI/edit#heading=h.2jljo0ndu4ud).

Notes:
When using the[ migration-validator](https://github.com/fcrepo-exts/fcrepo-migration-validator), we should enable checksum validation. 

```
-C, --checksum   Enable checksum validations of datastreams
  -a, --algorithm=<algorithm>
                   The digest algorithm to use during checksum validation:
                     sha256, sha512
                     Default: sha512
```

For basic acceptance criteria, see #34.

**Comment by kbowaterskelly** [comment]
https://github.com/fcrepo-exts/fcrepo-migration-validator

**Comment by eporter23** [comment]
All migrated except for emory:fj9p7 which fails with
WARN 19:51:02.762 (InternalIDResolver) Index exists at "/home/fedora/migration-utils/target/index" and will be used. To clear index, simply delete this directory and re-run the application.
ERROR 19:51:29.413 (Migrator) MIGRATION_FAILURE: UNREADABLE_OBJECT: message="Number of accept requests does not align with expected PID value! index: 10, pid: emory:rhrbf, expected pid: emory:fj9p7"
java.lang.IllegalStateException: Number of accept requests does not align with expected PID value! index: 10, pid: emory:rhrbf, expected pid: emory:fj9p7
at org.fcrepo.migration.pidlist.ResumePidListManager.accept(ResumePidListManager.java:130)
at org.fcrepo.migration.Migrator.acceptPid(Migrator.java:200)
at org.fcrepo.migration.Migrator.run(Migrator.java:158)
at org.fcrepo.migration.PicocliMigrator.call(PicocliMigrator.java:337)
at org.fcrepo.migration.PicocliMigrator.call(PicocliMigrator.java:51)
at picocli.CommandLine.executeUserObject(CommandLine.java:1743)
at picocli.CommandLine.access$900(CommandLine.java:145)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1935)
at picocli.CommandLine.execute(CommandLine.java:1864)
at org.fcrepo.migration.PicocliMigrator.main(PicocliMigrator.java:179)

**Comment by jcrompton42** [comment]
full results can be viewed here: https://emory-my.sharepoint.com/:u:/g/personal/jcrompt_emory_edu/ET-vA-e5RcxPnBmcFMLGd_YBnjQ8FbclrVB6Vs2TcYbR-w?e=i1JxmY

**Comment by eporter23** [comment]
We had metadata errors on 2 other PIDs but we think that was caused by modifications happening in the sandbox while the validation was being run. Those 2 pids did create successfully.
